version: '3.8'  # or any compatible version
services:
  pong_game:
    build:
      context: ./game/
      dockerfile: Dockerfile
    container_name: game
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
      - DB_NAME=pong_db
      - DB_USER=postgres
      - DB_PASSWORD=123
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     container_name: postgres_db
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=123
#       - POSTGRES_DB=pong_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/Users/nbouhali/goinfre/postgresql/data

# volumes:
#   postgres_data: