# Generated by Django 3.2.25 on 2025-01-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygoogle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
