# Generated by Django 3.2.7 on 2025-01-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygoogle', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
