# Generated by Django 3.2.7 on 2025-01-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoogle', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pics/dd.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
