# Generated by Django 3.2.7 on 2025-01-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygoogle', '0006_alter_userprofile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
