# Generated by Django 3.2.7 on 2025-02-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mygoogle', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userrrr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernnnnname', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_nameeee', models.CharField(max_length=100)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
