# Generated by Django 3.2.7 on 2025-02-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoogle', '0010_auto_20250217_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank=True, default='/media/defaultprofilepic.png', max_length=100, null=True),
        ),
    ]
