# Generated by Django 3.2.7 on 2025-03-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoogle', '0011_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank=True, default='/media/defaultprofilepic.png', max_length=100),
        ),
    ]
