# Generated by Django 4.2.19 on 2025-03-19 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mygoogle', '0017_alter_userprofile_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_played', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
