# Generated by Django 5.2b1 on 2025-03-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoogle', '0017_alter_userprofile_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
